import { StyleSheet } from 'react-native';
import { Brand, Inter } from '../constants/brand';

export const authStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: Brand.background },
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
    paddingBottom: 40,
  },
  brandBlock: {
    alignItems: 'center',
    marginBottom: 28,
  },
  logo: {
    width: 88,
    height: 88,
    marginBottom: 16,
  },
  brandName: {
    fontSize: 22,
    fontFamily: Inter.bold,
    color: Brand.text,
    letterSpacing: -0.4,
    marginBottom: 4,
  },
  title: {
    fontSize: 24,
    fontFamily: Inter.bold,
    color: Brand.text,
    textAlign: 'center',
    marginBottom: 6,
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 14,
    fontFamily: Inter.regular,
    color: Brand.textMuted,
    textAlign: 'center',
  },
  formCard: {
    backgroundColor: Brand.surface,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: Brand.border,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  errorBox: {
    backgroundColor: Brand.dangerBg,
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
  },
  errorText: {
    color: Brand.danger,
    fontSize: 13,
    fontFamily: Inter.medium,
  },
  label: {
    fontSize: 13,
    fontFamily: Inter.semibold,
    color: Brand.text,
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: Inter.regular,
    backgroundColor: Brand.background,
    color: Brand.text,
  },
  primaryBtn: {
    marginTop: 22,
    backgroundColor: Brand.primary,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  primaryBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: Inter.bold,
  },
  btnDisabled: { opacity: 0.6 },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: Brand.border },
  dividerText: {
    marginHorizontal: 12,
    fontSize: 12,
    fontFamily: Inter.medium,
    color: Brand.textSubtle,
  },
  googleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 12,
    paddingVertical: 13,
    backgroundColor: Brand.surface,
    marginBottom: 4,
  },
  googleBtnText: {
    fontSize: 15,
    fontFamily: Inter.semibold,
    color: Brand.text,
  },
  linkRow: { marginTop: 22, alignItems: 'center' },
  linkText: {
    fontSize: 13,
    fontFamily: Inter.regular,
    color: Brand.textMuted,
  },
  linkAccent: {
    color: Brand.primary,
    fontFamily: Inter.bold,
  },
});
