import { StyleSheet } from 'react-native';
import { Brand, Inter } from '../constants/brand';

export const formStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: Brand.background },
  safeArea: { flex: 1, backgroundColor: Brand.background },
  container: {
    padding: 16,
    paddingBottom: 40,
    flexGrow: 1,
    backgroundColor: Brand.background,
  },
  title: {
    fontSize: 22,
    fontFamily: Inter.bold,
    color: Brand.text,
    letterSpacing: -0.3,
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 13,
    fontFamily: Inter.semibold,
    color: Brand.textMuted,
    marginTop: 20,
    marginBottom: 8,
  },
  label: {
    fontSize: 13,
    fontFamily: Inter.semibold,
    color: Brand.text,
    marginTop: 12,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    fontFamily: Inter.regular,
    backgroundColor: Brand.surface,
    color: Brand.text,
  },
  notesInput: {
    height: 88,
    textAlignVertical: 'top',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Brand.border,
    backgroundColor: Brand.surface,
  },
  chipSelected: {
    backgroundColor: Brand.primary,
    borderColor: Brand.primary,
  },
  chipText: {
    fontSize: 13,
    fontFamily: Inter.medium,
    color: Brand.text,
  },
  chipTextSelected: {
    color: '#FFFFFF',
  },
  primaryButton: {
    marginTop: 24,
    backgroundColor: Brand.primary,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  primaryButtonDisabled: { opacity: 0.6 },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: Inter.bold,
  },
  outlineButton: {
    marginTop: 8,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 12,
    paddingVertical: 12,
    backgroundColor: Brand.surface,
  },
  outlineButtonText: {
    fontSize: 14,
    fontFamily: Inter.semibold,
    color: Brand.primary,
  },
  successButton: {
    marginTop: 12,
    backgroundColor: Brand.success,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  whatsAppButton: {
    marginTop: 10,
    backgroundColor: '#25D366',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  cancelButton: {
    marginTop: 12,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: Brand.dangerBg,
  },
  cancelButtonText: {
    color: Brand.danger,
    fontSize: 15,
    fontFamily: Inter.semibold,
  },
  card: {
    backgroundColor: Brand.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Brand.border,
  },
  cardTitle: {
    fontSize: 15,
    fontFamily: Inter.semibold,
    color: Brand.text,
    marginBottom: 4,
  },
  cardSub: {
    fontSize: 13,
    fontFamily: Inter.regular,
    color: Brand.textMuted,
    marginTop: 2,
  },
});
