import { StyleSheet } from 'react-native';
import { Brand, Inter } from '../constants/brand';

export const screenStyles = StyleSheet.create({
  container: {
    padding: 16,
    paddingBottom: 40,
    backgroundColor: Brand.background,
  },
  title: {
    fontSize: 22,
    fontFamily: Inter.bold,
    color: Brand.text,
    letterSpacing: -0.3,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    fontFamily: Inter.regular,
    color: Brand.textMuted,
    marginBottom: 16,
    lineHeight: 20,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.surface,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 12,
    height: 48,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: Inter.regular,
    color: Brand.text,
    height: 48,
  },
  primaryButton: {
    backgroundColor: Brand.primary,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 10,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: Inter.bold,
  },
  outlineButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 12,
    paddingVertical: 12,
    backgroundColor: Brand.surface,
  },
  outlineButtonText: {
    color: Brand.text,
    fontSize: 13,
    fontFamily: Inter.semibold,
  },
  secondaryRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 24,
  },
  loadingText: {
    fontSize: 14,
    fontFamily: Inter.medium,
    color: Brand.textMuted,
  },
  emptyState: {
    alignItems: 'center',
    marginTop: 48,
    paddingHorizontal: 24,
  },
  emptyTitle: {
    fontSize: 16,
    fontFamily: Inter.semibold,
    color: Brand.textMuted,
    marginBottom: 6,
    textAlign: 'center',
  },
  emptyHint: {
    fontSize: 13,
    fontFamily: Inter.regular,
    color: Brand.textSubtle,
    textAlign: 'center',
    lineHeight: 20,
  },
  surfaceCard: {
    backgroundColor: Brand.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Brand.border,
    padding: 16,
    marginBottom: 14,
  },
});
